server:
    port: 8008
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&characterEncoding=utf-8
        username: root
        password: 123456
    profiles:
        active: dev
    application:
        name: service-statistics
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    # 服务发现
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
# 开启熔断机制
feign:
    hystrix:
        enabled: true